# Generated by Django 3.1.2 on 2020-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_element_note_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='next',
        ),
        migrations.RemoveField(
            model_name='step',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
